Pop up Window
mwanawabangona/mobile-version-2 pull request #12
Opened 2021-10-06 22:14 UTC by mwanawabangona

- Add Html
- Add Css
- Add JavaScript
- Add Linters

2021-10-06 22:26 UTC, DanteAlonsoHT requested changes
<h1> Status: Required Changes 🚫 </h1>

Hi @mwanawabangona, 

Good job so far, I really love your design and the way you use to make the popup window! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
### _Check the comments under the review._ 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 22:26 UTC, DanteAlonsoHT commented on main.js
> +}
- [ ] Add responsive design for your popup, in the image below you can see how it looks like in a mobile version:
- [ ] Add more padding for your main content which contain all your information in your popup window, you can see that it is so close (check the yellow color in the image below)
- [ ] [OPTIONAL] Add the next CSS attribute to improve the UX in your app:
```
button:hover {
  cursor: pointer;
}
```

![image](https://user-images.githubusercontent.com/60164239/136291768-2788235b-8104-4e6f-a723-755714c45402.png)

2021-10-07 11:06 UTC, mwanawabangona commented on main.js
> +}
done, thank you

2021-10-07 12:03 UTC, rloterh commented on main.js
> +}
This aspect needs further improvements.

2021-10-07 12:07 UTC, mwanawabangona commented
what improvements, should implement

On Thu, Oct 7, 2021 at 2:03 PM Robert Loterh ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In main.js
> <https://github.com/mwanawabangona/mobile-version-2/pull/12#discussion_r724113879>
> :
>
> > +function changePopup(order) {
> +  tags.innerHTML = '';
> +
> +  const project = data[`project${order}`];
> +  nameID.innerHTML = project.name;
> +  img.src = project.img;
> +  companyName.innerHTML = project.companyName;
> +  job.innerHTML = project.job;
> +  year.innerHTML = project.year;
> +  descrition.innerHTML = project.decription;
> +  const tagsLength = project.tags.length;
> +  for (let i = 0; i < tagsLength; i += 1) {
> +    const element = document.createElement('li');
> +    element.innerHTML = `${project.tags[i]}`;
> +    tags.appendChild(element);
> +  }
> +  openPopUp();
> +}
>
> This aspect needs further improvements.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mwanawabangona/mobile-version-2/pull/12#discussion_r724113879>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APZJQIR4PETPLJ7NJJKVEV3UFWEC3ANCNFSM5FP3IR7A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-07 12:16 UTC, rloterh requested changes
Hi Ellis, 

You did great on this project, and for making the changes requested by the previous reviewer! 👏👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- No linter errors

## Required Changes ♻️
_Kindly check the comments above, made below /above the reviews of the previous code reviewer(s)**. Kindly take your time to correctly review those issues outlined by the previous code reviewers, and please check to see that the changes are working as intended._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider the comments marked **[OPTIONAL]** under this review:

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-07 12:16 UTC, rloterh commented on main.js
> +function validationEmail(e) {
- [ ] OPTIONAL
It is a nice idea to prefer _arrow functions_ over normal functions, so as to keep your _function_ syntax simpler and cleaner.

2021-10-07 12:16 UTC, rloterh commented on main.js
> +  openPopUp();
- [ ] You did a great job by adding paddings around the contents of the _popup window_ for the Desktop screens. However, the  _popup window_  for mobile screens needs some spacing around the contents, as can be seen in the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122). Kindly endeavor to improve upon this aspect.

**Your pop-up window (mobile screen):**
![image](https://user-images.githubusercontent.com/12745474/136381602-afaddcc1-cf88-4e38-864b-482ece09e5b5.png)



**The original pop-up window (mobile screen):**
![image](https://user-images.githubusercontent.com/12745474/136381894-a781445b-43cf-4f8a-b7c7-4106a1841cb6.png)

2021-10-07 12:23 UTC, mwanawabangona commented on main.js
> +  openPopUp();
Hi, this works just fine on my browser, I don't why it is showing you like that, if possible I would like to schedule a zoom call so I show you

2021-12-28 14:05 UTC, closed without merging